import "./globals.css";
import { Noto_Sans_KR, Noto_Serif_Malayalam, Noto_Serif_Tamil, Tajawal, Hind, Roboto_Slab } from 'next/font/google';

// Load fonts with subsets and weights as needed
const malayalam = Noto_Serif_Malayalam({ subsets: ['latin'], weight: ['400'] });
const tamil = Noto_Serif_Tamil({ subsets: ['latin'], weight: ['400'] });
const arabic = Tajawal({ subsets: ['latin'], weight: ['400'] });
const hindi = Hind({ subsets: ['latin'], weight: ['400'] });
const korean = Noto_Sans_KR({ subsets: ['latin'], weight: ['400'] });
const roboto = Roboto_Slab({ subsets: ['latin'], weight: ['400'] });

export const metadata = {
  title: "Portfolio",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${malayalam.className} ${tamil.className} ${arabic.className} ${hindi.className} ${korean.className} ${roboto.className}`}>
        {children}
      </body>
    </html>
  );
}